name = "Aethelgard"
version = "0.1"

# The engine will recursively scan these folders for .toml files
# and register them based on the 'id' found inside the file.
content_directories = [
    "creatures",
    "items",
    "classes",
    "races"
]

# Areas are handled slightly differently (loaded immediately to spawn the world)
area_directories = [
    "areas"
]