id = "goblin_grunt"
name = "Goblin Grunt"
description = "A short, wiry humanoid."

[stats]
strength = 11
dexterity = 15
# ... other stats

[combat]
natural_armor = 1  # Small size / thick skin
base_attack_bonus = 1
xp_reward = 500 #gen test

[vitals]
max_hp = 6